# Generated by Django 4.2.7 on 2023-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAbfragen',
            fields=[
                ('tabfrage', models.DateTimeField(db_column='tAbfrage', db_comment='Zeitpunkt der Abfrage', primary_key=True, serialize=False)),
                ('sfeldname', models.CharField(db_column='sFeldname', db_comment='Name des Solarfeldes', max_length=10)),
                ('dlongitude', models.FloatField(blank=True, db_column='dLongitude', db_comment='Längengrad des Standorts', null=True)),
                ('dlatitude', models.FloatField(blank=True, db_column='dLatitude', db_comment='Breitengrad des Standortes', null=True)),
                ('tmodelrun', models.DateTimeField(blank=True, db_column='tModelRun', db_comment='Zeitpunkt des Prognoselaufs bei Meteoblue', null=True)),
                ('tmodelrunupdate', models.DateTimeField(blank=True, db_column='tModelRunUpdate', db_comment='Zeitpunkt des Prognoseupdates bei Meteoblue', null=True)),
                ('dkwpeak', models.FloatField(blank=True, db_column='dkWPeak', db_comment='Kilowattpeak der installierten Solarkollektoren', null=True)),
                ('ineigung', models.IntegerField(blank=True, db_column='iNeigung', db_comment='Neigung der Solarmodule, z.B. 30 Grad', null=True)),
                ('irichtung', models.IntegerField(blank=True, db_column='iRichtung', db_comment='Ausrichtung der Solarmodule, z.B. 180 (Süd)', null=True)),
                ('deffizienz', models.FloatField(blank=True, db_column='dEffizienz', db_comment='Effizienz der Solarmodule, 0.2 ...1', null=True)),
            ],
            options={
                'db_table': 't_abfragen',
                'db_table_comment': 'speichert den Zeitpunkt der Abfrage der Solarprognose mit den wichtigsten Parametern\r\nabgefragt mit https://docs.meteoblue.com/en/weather-apis/packages-api/forecast-data#pv-pro \r\nin mb_pvpro.py',
                'get_latest_by': 'tabfrage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPrognose',
            fields=[
                ('stunde', models.DateTimeField(db_column='Stunde', db_comment='Datum und Uhrzeit der  Ertrags-Stunde, da die backwards-Datenreihe übernommen wird, geben die P-Werte wieder, wieviele kWh bis zu dieser Stunde erwartet werden', primary_key=True, serialize=False)),
                ('feldname', models.CharField(db_column='Feldname', db_comment='Name des Solarfeldes', max_length=10)),
                ('p24', models.FloatField(blank=True, db_column='P24', null=True)),
                ('p12', models.FloatField(blank=True, db_column='P12', null=True)),
                ('p6', models.FloatField(blank=True, db_column='P6', null=True)),
                ('p3', models.FloatField(blank=True, db_column='P3', null=True)),
                ('p1', models.FloatField(blank=True, db_column='P1', null=True)),
            ],
            options={
                'db_table': 't_prognose',
                'db_table_comment': 'Speichert zu jeder Stunde die 24-, 12-, 6-, 3- und 1-Stunden-Prognose\r\nabgefragt mit https://docs.meteoblue.com/en/weather-apis/packages-api/forecast-data#pv-pro \r\nin mb_pvpro.py',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VPrognoseStunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stunde', models.DateTimeField(db_column='Stunde', db_comment='Datum und Uhrzeit der  Ertrags-Stunde, da die backwards-Datenreihe übernommen wird, geben die P-Werte wieder, wieviele kWh bis zu dieser Stunde erwartet werden')),
                ('prognose', models.FloatField(blank=True, db_column='Prognose', null=True)),
            ],
            options={
                'db_table': 'v_prognose_stunde',
                'get_latest_by': 'stunde',
                'managed': False,
            },
        ),
    ]
